version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  lint:
    docker:
      - image: cimg/python:3.12.6
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            python -m pip install --upgrade pip
            pip install flake8
      - run:
          name: Lint the code
          command: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Checking if lint passed
          command: |
            if flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | grep -q "0"; then
              echo "Lint has passed and ready to merge"
            else
              echo "Lint failed, fix the issues"
              exit 1
            fi

workflows:
  pr-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - lint:
          requires:
            - say-hello
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
